CC=g++ #use this compiler
CFLAGS= -Wall # flags for the compiler yo

###############¤#¤######################
# I THREW THE EXCEPTION TO THE GROUND ##
#    I WONT BE PART OF YOUR SYSTEM    ##
# 	           IM AN ADULT			  ##
########################################

#makes (compiles and run) the file first
first: stack.c -o stack.h 
	gcc stack stack.c stack.o -o -I 



